### PR TITLE
refactoring: MqttBroker, "broker" -> "mqtt_client"

### PR DESCRIPTION
**Pull request by dg6nee**
refactoring: MqttBroker contains a member variable with the name "broker". This is quite misleading and makes the code harder to understand, as this member is a mqtt _client_ -> renaming from "broker" to "mqtt_client"

### CODE REVIEW

**Review by hsaturn — COMMENTED** [review]
I often see this PR but never could accept it as is.
But you're right the code is ugly.
broker is a connection to an external broker when *this is a proxy.
I did not reject this PR because I have something to do. But renaming broker to mqtt_client is more unclear.
Maybe a simple "using RemoteBroker = MqttClient" should do the trick.

**Comment by hsaturn** [comment]
> refactoring: MqttBroker contains a member variable with the name "broker". This is quite misleading and makes the code harder to understand, as this member is a mqtt _client_ -> renaming from "broker" to "mqtt_client"

MqttClient is used because it has almost all what is necessary for a MqttBroker to connect with a remote Broker.
When a broker links to another one, it must act as if it was a usual MqttClient. There is no link between brokers in Mqtt specification. And the zeroconf future feature wants this kind of link.

**Comment by alranel** [comment]
I vote for naming it `remote_broker` instead of `broker` :)
(Just the member variable; no need to rename the client class IMHO)

**Comment by hsaturn** [comment]
broker renamed to remote_broker

**Pull request closed without merging**
